export enum CategoryType {
	INCOME = 'INCOME',
	EXPENSE = 'EXPENSE',
}

export const OpenFinanceCategories = {
	// === INCOME ===
	INCOME: {
		id: '01000000',
		description: 'Income',
		translated: 'Renda',
		level1: 'Income',
		level2: null,
		level3: null,
	},
	SALARY: {
		id: '01010000',
		description: 'Salary',
		translated: 'Salário',
		level1: 'Income',
		level2: 'Salary',
		level3: null,
	},
	RETIREMENT: {
		id: '01020000',
		description: 'Retirement',
		translated: 'Aposentadoria',
		level1: 'Income',
		level2: 'Retirement',
		level3: null,
	},
	ENTREPRENEURIAL_ACTIVITIES: {
		id: '01030000',
		description: 'Entrepreneurial activities',
		translated: 'Atividades empreendedoras',
		level1: 'Income',
		level2: 'Entrepreneurial activities',
		level3: null,
	},
	GOVERNMENT_AID: {
		id: '01040000',
		description: 'Government aid',
		translated: 'Auxílio do governo',
		level1: 'Income',
		level2: 'Government aid',
		level3: null,
	},
	NON_RECURRING_INCOME: {
		id: '01050000',
		description: 'Non-recurring income',
		translated: 'Renda não recorrente',
		level1: 'Income',
		level2: 'Non-recurring income',
		level3: null,
	},

	// === LOANS AND FINANCING ===
	LATE_PAYMENT_OVERDRAFT_COSTS: {
		id: '02010000',
		description: 'Late payment and overdraft costs',
		translated: 'Custos de atraso e cheque especial',
		level1: 'Loans and Financing',
		level2: 'Late payment and overdraft costs',
		level3: null,
	},
	INTERESTS_CHARGED: {
		id: '02020000',
		description: 'Interests charged',
		translated: 'Juros cobrados',
		level1: 'Loans and Financing',
		level2: 'Interests charged',
		level3: null,
	},
	LOANS: {
		id: '02030000',
		description: 'Loans',
		translated: 'Empréstimos',
		level1: 'Loans and Financing',
		level2: 'Loans',
		level3: null,
	},
	REAL_ESTATE_FINANCING: {
		id: '02040000',
		description: 'Real estate financing',
		translated: 'Financiamento imobiliário',
		level1: 'Financing',
		level2: 'Real estate financing',
		level3: null,
	},
	VEHICLE_FINANCING: {
		id: '02050000',
		description: 'Vehicle financing',
		translated: 'Financiamento de veículo',
		level1: 'Financing',
		level2: 'Vehicle financing',
		level3: null,
	},
	STUDENT_LOAN: {
		id: '02060000',
		description: 'Student loan',
		translated: 'Financiamento estudantil',
		level1: 'Financing',
		level2: 'Student loan',
		level3: null,
	},

	// === INVESTMENTS ===
	AUTOMATIC_INVESTMENT: {
		id: '03010000',
		description: 'Automatic investment',
		translated: 'Investimento automático',
		level1: 'Investments',
		level2: 'Automatic investment',
		level3: null,
	},
	FIXED_INCOME: {
		id: '03020000',
		description: 'Fixed income',
		translated: 'Renda fixa',
		level1: 'Investments',
		level2: 'Fixed income',
		level3: null,
	},
	MUTUAL_FUNDS: {
		id: '03030000',
		description: 'Mutual funds',
		translated: 'Fundos de investimento',
		level1: 'Investments',
		level2: 'Mutual funds',
		level3: null,
	},
	VARIABLE_INCOME: {
		id: '03040000',
		description: 'Variable income',
		translated: 'Renda variável',
		level1: 'Investments',
		level2: 'Variable income',
		level3: null,
	},
	MARGIN: {
		id: '03050000',
		description: 'Margin',
		translated: 'Margem',
		level1: 'Investments',
		level2: 'Margin',
		level3: null,
	},
	PROCEEDS_INTERESTS_DIVIDENDS: {
		id: '03060000',
		description: 'Proceeds interests and dividends',
		translated: 'Proventos e dividendos',
		level1: 'Investments',
		level2: 'Proceeds interests and dividends',
		level3: null,
	},
	PENSION: {
		id: '03070000',
		description: 'Pension',
		translated: 'Pensão',
		level1: 'Investments',
		level2: 'Pension',
		level3: null,
	},

	// === SAME PERSON TRANSFER ===
	SAME_PERSON_TRANSFER_CASH: {
		id: '04010000',
		description: 'Same person transfer - Cash',
		translated: 'Transferência mesma pessoa - Dinheiro',
		level1: 'Same person transfer',
		level2: 'Cash',
		level3: null,
	},
	SAME_PERSON_TRANSFER_PIX: {
		id: '04020000',
		description: 'Same person transfer - PIX',
		translated: 'Transferência mesma pessoa - PIX',
		level1: 'Same person transfer',
		level2: 'PIX',
		level3: null,
	},
	SAME_PERSON_TRANSFER_TED: {
		id: '04030000',
		description: 'Same person transfer - TED',
		translated: 'Transferência mesma pessoa - TED',
		level1: 'Same person transfer',
		level2: 'TED',
		level3: null,
	},

	// === TRANSFERS ===
	TRANSFERS: {
		id: '05000000',
		description: 'Transfers',
		translated: 'Transferências',
		level1: 'Transfers',
		level2: null,
		level3: null,
	},
	TRANSFER_BANK_SLIP: {
		id: '05010000',
		description: 'Transfer - Bank slip (Boleto)',
		translated: 'Transferência - Boleto',
		level1: 'Transfers',
		level2: 'Bank slip',
		level3: null,
	},
	TRANSFER_CASH: {
		id: '05020000',
		description: 'Transfer - Cash',
		translated: 'Transferência - Dinheiro',
		level1: 'Transfers',
		level2: 'Cash',
		level3: null,
	},
	TRANSFER_CHECK: {
		id: '05030000',
		description: 'Transfer - Check',
		translated: 'Transferência - Cheque',
		level1: 'Transfers',
		level2: 'Check',
		level3: null,
	},
	TRANSFER_DOC: {
		id: '05040000',
		description: 'Transfer - DOC',
		translated: 'Transferência - DOC',
		level1: 'Transfers',
		level2: 'DOC',
		level3: null,
	},
	TRANSFER_FOREIGN_EXCHANGE: {
		id: '05050000',
		description: 'Transfer - Foreign exchange',
		translated: 'Transferência - Câmbio',
		level1: 'Transfers',
		level2: 'Foreign exchange',
		level3: null,
	},
	TRANSFER_INTERNAL: {
		id: '05060000',
		description: 'Transfer - Internal',
		translated: 'Transferência - Interna',
		level1: 'Transfers',
		level2: 'Internal',
		level3: null,
	},
	TRANSFER_PIX: {
		id: '05070000',
		description: 'Transfer - PIX',
		translated: 'Transferência - PIX',
		level1: 'Transfers',
		level2: 'PIX',
		level3: null,
	},
	TRANSFER_TED: {
		id: '05080000',
		description: 'Transfer - TED',
		translated: 'Transferência - TED',
		level1: 'Transfers',
		level2: 'TED',
		level3: null,
	},

	// === CREDIT CARD PAYMENT ===
	CREDIT_CARD_PAYMENT: {
		id: '06000000',
		description: 'Credit card payment',
		translated: 'Pagamento de cartão de crédito',
		level1: 'Credit card payment',
		level2: null,
		level3: null,
	},

	// === THIRD-PARTY TRANSFERS ===
	THIRD_PARTY_TRANSFER_BANK_SLIP: {
		id: '07010000',
		description: 'Third-party transfer - Bank slip',
		translated: 'Transferência terceiros - Boleto',
		level1: 'Third-party transfers',
		level2: 'Bank slip',
		level3: null,
	},
	THIRD_PARTY_TRANSFER_DEBIT_CARD: {
		id: '07020000',
		description: 'Third-party transfer - Debit card',
		translated: 'Transferência terceiros - Cartão de débito',
		level1: 'Third-party transfers',
		level2: 'Debit card',
		level3: null,
	},
	THIRD_PARTY_TRANSFER_DOC: {
		id: '07030000',
		description: 'Third-party transfer - DOC',
		translated: 'Transferência terceiros - DOC',
		level1: 'Third-party transfers',
		level2: 'DOC',
		level3: null,
	},
	THIRD_PARTY_TRANSFER_PIX: {
		id: '07040000',
		description: 'Third-party transfer - PIX',
		translated: 'Transferência terceiros - PIX',
		level1: 'Third-party transfers',
		level2: 'PIX',
		level3: null,
	},
	THIRD_PARTY_TRANSFER_TED: {
		id: '07050000',
		description: 'Third-party transfer - TED',
		translated: 'Transferência terceiros - TED',
		level1: 'Third-party transfers',
		level2: 'TED',
		level3: null,
	},

	// === LEGAL OBLIGATIONS ===
	BLOCKED_BALANCES: {
		id: '08010000',
		description: 'Blocked balances',
		translated: 'Saldos bloqueados',
		level1: 'Legal obligations',
		level2: 'Blocked balances',
		level3: null,
	},
	ALIMONY: {
		id: '08020000',
		description: 'Alimony',
		translated: 'Pensão alimentícia',
		level1: 'Legal obligations',
		level2: 'Alimony',
		level3: null,
	},

	// === SERVICES ===
	TELECOMMUNICATIONS_INTERNET: {
		id: '09010000',
		description: 'Internet',
		translated: 'Internet',
		level1: 'Services',
		level2: 'Telecommunications',
		level3: 'Internet',
	},
	TELECOMMUNICATIONS_MOBILE: {
		id: '09020000',
		description: 'Mobile',
		translated: 'Celular',
		level1: 'Services',
		level2: 'Telecommunications',
		level3: 'Mobile',
	},
	TELECOMMUNICATIONS_TV: {
		id: '09030000',
		description: 'TV',
		translated: 'TV',
		level1: 'Services',
		level2: 'Telecommunications',
		level3: 'TV',
	},
	EDUCATION_ONLINE_COURSES: {
		id: '09040000',
		description: 'Online Courses',
		translated: 'Cursos online',
		level1: 'Services',
		level2: 'Education',
		level3: 'Online Courses',
	},
	EDUCATION_UNIVERSITY: {
		id: '09050000',
		description: 'University',
		translated: 'Universidade',
		level1: 'Services',
		level2: 'Education',
		level3: 'University',
	},
	EDUCATION_SCHOOL: {
		id: '09060000',
		description: 'School',
		translated: 'Escola',
		level1: 'Services',
		level2: 'Education',
		level3: 'School',
	},
	EDUCATION_KINDERGARTEN: {
		id: '09070000',
		description: 'Kindergarten',
		translated: 'Jardim de infância',
		level1: 'Services',
		level2: 'Education',
		level3: 'Kindergarten',
	},
	WELLNESS_GYMS: {
		id: '09080000',
		description: 'Gyms and fitness centers',
		translated: 'Academias e centros de fitness',
		level1: 'Services',
		level2: 'Wellness and fitness',
		level3: 'Gyms and fitness centers',
	},
	WELLNESS_SPORTS_PRACTICE: {
		id: '09090000',
		description: 'Sports practice',
		translated: 'Prática esportiva',
		level1: 'Services',
		level2: 'Wellness and fitness',
		level3: 'Sports practice',
	},
	WELLNESS: {
		id: '09100000',
		description: 'Wellness',
		translated: 'Bem-estar',
		level1: 'Services',
		level2: 'Wellness and fitness',
		level3: 'Wellness',
	},

	// === SHOPPING ===
	ONLINE_SHOPPING: {
		id: '10010000',
		description: 'Online shopping',
		translated: 'Compras online',
		level1: 'Shopping',
		level2: 'Online shopping',
		level3: null,
	},
	ELECTRONICS: {
		id: '10020000',
		description: 'Electronics',
		translated: 'Eletrônicos',
		level1: 'Shopping',
		level2: 'Electronics',
		level3: null,
	},
	PET_SUPPLIES: {
		id: '10030000',
		description: 'Pet supplies and vet',
		translated: 'Produtos para animais e veterinário',
		level1: 'Shopping',
		level2: 'Pet supplies and vet',
		level3: null,
	},
	CLOTHING: {
		id: '10040000',
		description: 'Clothing',
		translated: 'Roupas',
		level1: 'Shopping',
		level2: 'Clothing',
		level3: null,
	},
	KIDS_TOYS: {
		id: '10050000',
		description: 'Kids and toys',
		translated: 'Crianças e brinquedos',
		level1: 'Shopping',
		level2: 'Kids and toys',
		level3: null,
	},
	BOOKSTORE: {
		id: '10060000',
		description: 'Bookstore',
		translated: 'Livraria',
		level1: 'Shopping',
		level2: 'Bookstore',
		level3: null,
	},
	SPORTS_GOODS: {
		id: '10070000',
		description: 'Sports goods',
		translated: 'Artigos esportivos',
		level1: 'Shopping',
		level2: 'Sports goods',
		level3: null,
	},
	OFFICE_SUPPLIES: {
		id: '10080000',
		description: 'Office Supplies',
		translated: 'Material de escritório',
		level1: 'Shopping',
		level2: 'Office Supplies',
		level3: null,
	},
	CASHBACK: {
		id: '10090000',
		description: 'Cashback',
		translated: 'Cashback',
		level1: 'Shopping',
		level2: 'Cashback',
		level3: null,
	},

	// === DIGITAL SERVICES ===
	GAMING: {
		id: '11010000',
		description: 'Gaming',
		translated: 'Jogos',
		level1: 'Digital services',
		level2: 'Gaming',
		level3: null,
	},
	VIDEO_STREAMING: {
		id: '11020000',
		description: 'Video streaming',
		translated: 'Streaming de vídeo',
		level1: 'Digital services',
		level2: 'Video streaming',
		level3: null,
	},
	MUSIC_STREAMING: {
		id: '11030000',
		description: 'Music streaming',
		translated: 'Streaming de música',
		level1: 'Digital services',
		level2: 'Music streaming',
		level3: null,
	},

	// === FOOD AND DRINKS ===
	EATING_OUT: {
		id: '12010000',
		description: 'Eating out',
		translated: 'Comer fora',
		level1: 'Food and drinks',
		level2: 'Eating out',
		level3: null,
	},
	FOOD_DELIVERY: {
		id: '12020000',
		description: 'Food delivery',
		translated: 'Entrega de comida',
		level1: 'Food and drinks',
		level2: 'Food delivery',
		level3: null,
	},

	// === TRAVEL ===
	AIRPORT_AIRLINES: {
		id: '13010000',
		description: 'Airport and airlines',
		translated: 'Aeroporto e companhias aéreas',
		level1: 'Travel',
		level2: 'Airport and airlines',
		level3: null,
	},
	ACCOMMODATION: {
		id: '13020000',
		description: 'Accommodation',
		translated: 'Hospedagem',
		level1: 'Travel',
		level2: 'Accommodation',
		level3: null,
	},
	MILEAGE_PROGRAMS: {
		id: '13030000',
		description: 'Mileage programs',
		translated: 'Programas de milhagem',
		level1: 'Travel',
		level2: 'Mileage programs',
		level3: null,
	},
	BUS_TICKETS: {
		id: '13040000',
		description: 'Bus tickets',
		translated: 'Passagens de ônibus',
		level1: 'Travel',
		level2: 'Bus tickets',
		level3: null,
	},

	// === DONATIONS ===
	DONATIONS: {
		id: '14000000',
		description: 'Donations',
		translated: 'Doações',
		level1: 'Donations',
		level2: null,
		level3: null,
	},

	// === GAMBLING ===
	LOTTERY: {
		id: '15010000',
		description: 'Lottery',
		translated: 'Loteria',
		level1: 'Gambling',
		level2: 'Lottery',
		level3: null,
	},
	ONLINE_BET: {
		id: '15020000',
		description: 'Online bet',
		translated: 'Aposta online',
		level1: 'Gambling',
		level2: 'Online bet',
		level3: null,
	},

	// === TAXES ===
	INCOME_TAXES: {
		id: '16010000',
		description: 'Income taxes',
		translated: 'Imposto de renda',
		level1: 'Taxes',
		level2: 'Income taxes',
		level3: null,
	},
	TAXES_ON_INVESTMENTS: {
		id: '16020000',
		description: 'Taxes on investments',
		translated: 'Impostos sobre investimentos',
		level1: 'Taxes',
		level2: 'Taxes on investments',
		level3: null,
	},
	TAX_ON_FINANCIAL_OPERATIONS: {
		id: '16030000',
		description: 'Tax on financial operations',
		translated: 'Imposto sobre operações financeiras',
		level1: 'Taxes',
		level2: 'Tax on financial operations',
		level3: null,
	},

	// === BANK FEES ===
	ACCOUNT_FEES: {
		id: '17010000',
		description: 'Account fees',
		translated: 'Tarifas de conta',
		level1: 'Bank fees',
		level2: 'Account fees',
		level3: null,
	},
	WIRE_ATM_FEES: {
		id: '17020000',
		description: 'Wire transfer fees and ATM fees',
		translated: 'Taxas de transferência e caixa eletrônico',
		level1: 'Bank fees',
		level2: 'Wire transfer fees and ATM fees',
		level3: null,
	},
	CREDIT_CARD_FEES: {
		id: '17030000',
		description: 'Credit card fees',
		translated: 'Taxas de cartão de crédito',
		level1: 'Bank fees',
		level2: 'Credit card fees',
		level3: null,
	},

	// === HOUSING ===
	RENT: {
		id: '18010000',
		description: 'Rent',
		translated: 'Aluguel',
		level1: 'Housing',
		level2: 'Rent',
		level3: null,
	},
	HOUSEWARE: {
		id: '18020000',
		description: 'Houseware',
		translated: 'Artigos para casa',
		level1: 'Housing',
		level2: 'Houseware',
		level3: null,
	},
	URBAN_LAND_TAX: {
		id: '18030000',
		description: 'Urban land and building tax',
		translated: 'Imposto predial e territorial urbano',
		level1: 'Housing',
		level2: 'Urban land and building tax',
		level3: null,
	},

	// === UTILITIES ===
	WATER: {
		id: '19010000',
		description: 'Water',
		translated: 'Água',
		level1: 'Utilities',
		level2: 'Water',
		level3: null,
	},
	ELECTRICITY: {
		id: '19020000',
		description: 'Electricity',
		translated: 'Eletricidade',
		level1: 'Utilities',
		level2: 'Electricity',
		level3: null,
	},
	GAS: {
		id: '19030000',
		description: 'Gas',
		translated: 'Gás',
		level1: 'Utilities',
		level2: 'Gas',
		level3: null,
	},

	// === HEALTHCARE ===
	DENTIST: {
		id: '20010000',
		description: 'Dentist',
		translated: 'Dentista',
		level1: 'Healthcare',
		level2: 'Dentist',
		level3: null,
	},
	PHARMACY: {
		id: '20020000',
		description: 'Pharmacy',
		translated: 'Farmácia',
		level1: 'Healthcare',
		level2: 'Pharmacy',
		level3: null,
	},
	OPTOMETRY: {
		id: '20030000',
		description: 'Optometry',
		translated: 'Oftalmologia',
		level1: 'Healthcare',
		level2: 'Optometry',
		level3: null,
	},
	HOSPITALS_CLINICS: {
		id: '20040000',
		description: 'Hospital clinics and labs',
		translated: 'Hospitais, clínicas e laboratórios',
		level1: 'Healthcare',
		level2: 'Hospital clinics and labs',
		level3: null,
	},

	// === TRANSPORTATION ===
	TAXI_RIDE_HAILING: {
		id: '21010000',
		description: 'Taxi and ride-hailing',
		translated: 'Táxi e transporte por aplicativo',
		level1: 'Transportation',
		level2: 'Taxi and ride-hailing',
		level3: null,
	},
	PUBLIC_TRANSPORT: {
		id: '21020000',
		description: 'Public transportation',
		translated: 'Transporte público',
		level1: 'Transportation',
		level2: 'Public transportation',
		level3: null,
	},
	CAR_RENTAL: {
		id: '21030000',
		description: 'Car rental',
		translated: 'Aluguel de carros',
		level1: 'Transportation',
		level2: 'Car rental',
		level3: null,
	},
	BICYCLE: {
		id: '21040000',
		description: 'Bicycle',
		translated: 'Bicicleta',
		level1: 'Transportation',
		level2: 'Bicycle',
		level3: null,
	},

	// === AUTOMOTIVE ===
	GAS_STATIONS: {
		id: '22010000',
		description: 'Gas stations',
		translated: 'Postos de gasolina',
		level1: 'Automotive',
		level2: 'Gas stations',
		level3: null,
	},
	PARKING: {
		id: '22020000',
		description: 'Parking',
		translated: 'Estacionamento',
		level1: 'Automotive',
		level2: 'Parking',
		level3: null,
	},
	TOLLS: {
		id: '22030000',
		description: 'Tolls',
		translated: 'Pedágios',
		level1: 'Automotive',
		level2: 'Tolls',
		level3: null,
	},
	VEHICLE_OWNERSHIP_TAXES: {
		id: '22040000',
		description: 'Vehicle ownership taxes and fees',
		translated: 'IPVA e taxas de veículos',
		level1: 'Automotive',
		level2: 'Vehicle ownership taxes and fees',
		level3: null,
	},
	VEHICLE_MAINTENANCE: {
		id: '22050000',
		description: 'Vehicle maintenance',
		translated: 'Manutenção de veículos',
		level1: 'Automotive',
		level2: 'Vehicle maintenance',
		level3: null,
	},
	TRAFFIC_TICKETS: {
		id: '22060000',
		description: 'Traffic tickets',
		translated: 'Multas de trânsito',
		level1: 'Automotive',
		level2: 'Traffic tickets',
		level3: null,
	},

	// === INSURANCE ===
	LIFE_INSURANCE: {
		id: '23010000',
		description: 'Life insurance',
		translated: 'Seguro de vida',
		level1: 'Insurance',
		level2: 'Life insurance',
		level3: null,
	},
	HOME_INSURANCE: {
		id: '23020000',
		description: 'Home Insurance',
		translated: 'Seguro residencial',
		level1: 'Insurance',
		level2: 'Home Insurance',
		level3: null,
	},
	HEALTH_INSURANCE: {
		id: '23030000',
		description: 'Health insurance',
		translated: 'Plano de saúde',
		level1: 'Insurance',
		level2: 'Health insurance',
		level3: null,
	},
	VEHICLE_INSURANCE: {
		id: '23040000',
		description: 'Vehicle insurance',
		translated: 'Seguro de veículos',
		level1: 'Insurance',
		level2: 'Vehicle insurance',
		level3: null,
	},

	// === LEISURE ===
	LEISURE: {
		id: '24000000',
		description: 'Leisure',
		translated: 'Lazer',
		level1: 'Leisure',
		level2: null,
		level3: null,
	},
}

export type OpenFinanceCategoryID = keyof typeof OpenFinanceCategories
