global:
  scrape_interval: 15s
  evaluation_interval: 15s

remote_write:
  - url: http://mimir:9009/api/v1/push
    name: mimir
    send_exemplars: true

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  - job_name: "otel-collector"
    scrape_interval: 10s
    static_configs:
      - targets: ["otel-collector:8889"]
        labels:
          service: "otel-collector"

  - job_name: "prometheus"
    scrape_interval: 10s
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          service: "prometheus"

  - job_name: "node-exporter"
    scrape_interval: 10s
    static_configs:
      - targets: ["node-exporter:9100"]
        labels:
          service: "node-metrics"
    relabel_configs:
      - source_labels: [__address__]
        regex: ".*"
        target_label: instance
        replacement: "node-exporter"

  - job_name: "blackbox-exporter"
    scrape_interval: 10s
    static_configs:
      - targets: ["blackbox-exporter:9115"]
        labels:
          service: "blackbox-exporter"

  - job_name: "blackbox-http"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://api:4000/health # API health endpoint
          - http://grafana:3000 # Grafana
          - http://prometheus:9090 # Prometheus
          - http://tempo:3200/status # Tempo status
          - http://mimir:9009/ready # Mimir readiness
          - http://loki:3100/ready # Loki readiness
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: "blackbox-tcp"
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets:
          - postgres:5432 # PostgreSQL
          - otel-collector:4317 # OpenTelemetry Collector gRPC
          - otel-collector:4318 # OpenTelemetry Collector HTTP
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: "postgres-exporter"
    scrape_interval: 10s
    static_configs:
      - targets: ["postgres-exporter:9187"]
        labels:
          service: "postgres"
