apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo:3200
    access: proxy
    editable: true
    isDefault: false
    jsonData:
      tracesToLogs:
        datasourceUid: loki
        tags: ["job", "instance", "service.name", "service.namespace"]
        mappedTags: [{ key: "service.name", value: "service" }]
        mapTagNamesEnabled: true
        spanStartTimeShift: "-1h"
        spanEndTimeShift: "1h"
        filterByTraceID: true
        filterBySpanID: true
      nodeGraph:
        enabled: true
      search:
        hide: false
      serviceMap:
        datasourceUid: prometheus
      lokiSearch:
        datasourceUid: loki

  - name: Loki
    type: loki
    uid: loki
    url: http://loki:3100
    access: proxy
    editable: true
    isDefault: false
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "traceID=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"
          urlDisplayLabel: "View Trace"

  - name: Mimir
    type: prometheus
    uid: mimir
    url: http://mimir:9009/prometheus
    access: proxy
    editable: true
    isDefault: true
    jsonData:
      timeInterval: 15s
      httpMethod: GET
      exemplarTraceIdDestinations:
        - name: TraceID
          datasourceUid: tempo

  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
    access: proxy
    editable: true
    isDefault: false
    jsonData:
      timeInterval: 15s
      httpMethod: GET
      exemplarTraceIdDestinations:
        - name: TraceID
          datasourceUid: tempo
