# Mimir configuration for single-instance mode
multitenancy_enabled: false

common:
  storage:
    backend: filesystem
    filesystem:
      dir: /data/chunks

blocks_storage:
  storage_prefix: blocks
  bucket_store:
    sync_dir: /data/tsdb-sync
  tsdb:
    dir: /data/tsdb

compactor:
  data_dir: /data/compactor
  sharding_ring:
    kvstore:
      store: inmemory

distributor:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

ingester:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
    replication_factor: 1

ruler_storage:
  backend: filesystem
  filesystem:
    dir: /data/ruler-storage

alertmanager_storage:
  backend: filesystem
  filesystem:
    dir: /data/alertmanager

server:
  http_listen_port: 9009
  grpc_listen_port: 9095

store_gateway:
  sharding_ring:
    replication_factor: 1
    kvstore:
      store: inmemory

frontend:
  address: 127.0.0.1

frontend_worker:
  frontend_address: 127.0.0.1:9095

ruler:
  rule_path: /data/rules
  alertmanager_url: http://alertmanager:9093
  ring:
    kvstore:
      store: inmemory

limits:
  max_global_series_per_user: 1000000
  max_global_series_per_metric: 100000
  ingestion_rate: 10000
  ingestion_burst_size: 200000
