export const DATABASE_PROVIDER = 'DATA_SOURCE';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const DRUG_REPOSITORY = 'DRUG_REPOSITORY';
export const INDICATION_REPOSITORY = 'INDICATION_REPOSITORY';